# Generated by Django 5.1.7 on 2025-03-13 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oab', models.CharField(max_length=100)),
                ('nome_completo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=50)),
                ('tipo_processo', models.CharField(max_length=50)),
                ('acao', models.CharField(max_length=100)),
                ('contrato_envolvido', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=50)),
                ('valor_causa', models.FloatField()),
                ('vara', models.CharField(max_length=50)),
                ('fase', models.CharField(max_length=50)),
                ('instancia', models.CharField(max_length=50)),
                ('data_propositura', models.DateField()),
                ('processo_tramite', models.BooleanField(default=False)),
                ('processo_suspenso', models.BooleanField(default=False)),
                ('processo_extinto', models.BooleanField(default=False)),
                ('nome_autor', models.CharField(max_length=50, unique=True)),
                ('cpf_autor', models.CharField(max_length=14)),
                ('data_ultima_modificacao', models.DateField()),
                ('juiz', models.CharField(max_length=50)),
                ('numero_processo', models.CharField(max_length=50, unique=True)),
                ('advogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juridico.advogado')),
            ],
        ),
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('descricao', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunioes_autor', to='juridico.processo', to_field='nome_autor')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunioes_processo', to='juridico.processo', to_field='numero_processo')),
            ],
        ),
    ]
