# Generated by Django 5.1.7 on 2025-03-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0002_processo_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='descricao',
            field=models.TextField(),
        ),
    ]
