# Generated by Django 5.1.7 on 2025-03-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0003_alter_processo_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='processo_extinto',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='processo_suspenso',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='processo_tramite',
        ),
        migrations.AddField(
            model_name='processo',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
