# Generated by Django 5.1.7 on 2025-03-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0004_remove_processo_processo_extinto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
