# Generated by Django 5.1.7 on 2025-05-26 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0005_alter_processo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='advogado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='juridico.advogado'),
        ),
    ]
