# Generated by Django 5.1.7 on 2025-05-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juridico', '0006_alter_processo_advogado'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='advogado_nome',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
